spring:
  application:
    name: gulimall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.33.10:8848

    alicloud:
      access-key: --------------
      secret-key: ---------------
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: edu-0110
#      sms:
#        host: http://dfsns.market.alicloudapi.com
#        path: /data/send_sms
#        appCode:
server:
  port: 30001

logging:
  level:
    com.atguigu.gulimall.product: debug